-- SHW Digital Services admin panel setup for Supabase.
-- Run this in the Supabase SQL editor before using /admin.

create schema if not exists app_private;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function app_private.current_user_is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and is_admin = true
  );
$$;

revoke all on function app_private.current_user_is_admin() from public;
grant execute on function app_private.current_user_is_admin() to authenticated;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.website_metrics (
  id bigint generated by default as identity primary key,
  metric_name text not null,
  metric_value numeric not null default 0,
  period_start date,
  period_end date,
  source text,
  created_at timestamptz not null default now()
);

create table if not exists public.contracts (
  id bigint generated by default as identity primary key,
  generated_by uuid references auth.users(id) on delete set null default auth.uid(),
  service_type text not null,
  client_name text not null,
  client_business text,
  client_email text,
  contract_value numeric,
  deposit_percent numeric not null default 25,
  status text not null default 'draft',
  contract_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.audit_logs enable row level security;
alter table public.website_metrics enable row level security;
alter table public.contracts enable row level security;

create policy "profiles_select_self_or_admin"
  on public.profiles for select
  to authenticated
  using (id = (select auth.uid()) or app_private.current_user_is_admin());

create policy "audit_logs_admin_select"
  on public.audit_logs for select
  to authenticated
  using (app_private.current_user_is_admin());

create policy "audit_logs_admin_insert"
  on public.audit_logs for insert
  to authenticated
  with check (app_private.current_user_is_admin());

create policy "website_metrics_admin_select"
  on public.website_metrics for select
  to authenticated
  using (app_private.current_user_is_admin());

create policy "website_metrics_admin_insert"
  on public.website_metrics for insert
  to authenticated
  with check (app_private.current_user_is_admin());

create policy "contracts_admin_all"
  on public.contracts for all
  to authenticated
  using (app_private.current_user_is_admin())
  with check (app_private.current_user_is_admin());

grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant select, insert on public.audit_logs to authenticated;
grant select, insert on public.website_metrics to authenticated;
grant select, insert, update, delete on public.contracts to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- After creating your Supabase Auth user, make yourself admin with:
-- insert into public.profiles (id, email, is_admin)
-- select id, email, true from auth.users where email = 'your-email@example.com'
-- on conflict (id) do update set is_admin = true, email = excluded.email, updated_at = now();