-- SHW Digital Services admin panel and client portal setup for Supabase.
-- Run this in the Supabase SQL editor before using /admin or /client-portal.

create schema if not exists app_private;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  is_admin boolean not null default false,
  contact_name text,
  business_name text,
  phone text,
  address_line_1 text,
  address_line_2 text,
  city text,
  postcode text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists contact_name text;
alter table public.profiles add column if not exists business_name text;
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists address_line_1 text;
alter table public.profiles add column if not exists address_line_2 text;
alter table public.profiles add column if not exists city text;
alter table public.profiles add column if not exists postcode text;

create or replace function app_private.current_user_is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and is_admin = true
  );
$$;

revoke all on function app_private.current_user_is_admin() from public;
grant execute on function app_private.current_user_is_admin() to authenticated;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null default auth.uid(),
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.website_metrics (
  id bigint generated by default as identity primary key,
  metric_name text not null,
  metric_value numeric not null default 0,
  period_start date,
  period_end date,
  source text,
  created_at timestamptz not null default now()
);

create table if not exists public.contracts (
  id bigint generated by default as identity primary key,
  generated_by uuid references auth.users(id) on delete set null default auth.uid(),
  service_type text not null,
  client_name text not null,
  client_business text,
  client_email text,
  contract_value numeric,
  deposit_percent numeric not null default 25,
  status text not null default 'draft',
  contract_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.contract_payments (
  id bigint generated by default as identity primary key,
  contract_id bigint references public.contracts(id) on delete set null,
  client_email text not null,
  amount numeric not null,
  payment_type text not null default 'Contract payment',
  payment_status text not null default 'due',
  payment_url text,
  due_date date,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.client_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade default auth.uid(),
  client_email text not null,
  subject text not null,
  message text not null,
  status text not null default 'new',
  direction text not null default 'client_to_admin',
  parent_message_id bigint references public.client_messages(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.client_messages add column if not exists direction text not null default 'client_to_admin';
alter table public.client_messages add column if not exists parent_message_id bigint references public.client_messages(id) on delete set null;

create table if not exists public.knowledge_base (
  id bigint generated by default as identity primary key,
  title text not null,
  category text not null default 'General',
  content text not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.audit_logs enable row level security;
alter table public.website_metrics enable row level security;
alter table public.contracts enable row level security;
alter table public.contract_payments enable row level security;
alter table public.client_messages enable row level security;
alter table public.knowledge_base enable row level security;

drop policy if exists "profiles_select_self_or_admin" on public.profiles;
create policy "profiles_select_self_or_admin"
  on public.profiles for select
  to authenticated
  using (id = (select auth.uid()) or app_private.current_user_is_admin());

drop policy if exists "profiles_insert_self_or_admin" on public.profiles;
create policy "profiles_insert_self_or_admin"
  on public.profiles for insert
  to authenticated
  with check (id = (select auth.uid()) or app_private.current_user_is_admin());

drop policy if exists "profiles_update_self_or_admin" on public.profiles;
create policy "profiles_update_self_or_admin"
  on public.profiles for update
  to authenticated
  using (id = (select auth.uid()) or app_private.current_user_is_admin())
  with check (id = (select auth.uid()) or app_private.current_user_is_admin());

drop policy if exists "audit_logs_admin_select" on public.audit_logs;
create policy "audit_logs_admin_select"
  on public.audit_logs for select
  to authenticated
  using (app_private.current_user_is_admin());

drop policy if exists "audit_logs_admin_insert" on public.audit_logs;
create policy "audit_logs_admin_insert"
  on public.audit_logs for insert
  to authenticated
  with check (app_private.current_user_is_admin());

drop policy if exists "website_metrics_admin_select" on public.website_metrics;
create policy "website_metrics_admin_select"
  on public.website_metrics for select
  to authenticated
  using (app_private.current_user_is_admin());

drop policy if exists "website_metrics_admin_insert" on public.website_metrics;
create policy "website_metrics_admin_insert"
  on public.website_metrics for insert
  to authenticated
  with check (app_private.current_user_is_admin());

drop policy if exists "contracts_admin_all" on public.contracts;
create policy "contracts_admin_all"
  on public.contracts for all
  to authenticated
  using (app_private.current_user_is_admin())
  with check (app_private.current_user_is_admin());

drop policy if exists "contracts_client_select_by_email" on public.contracts;
create policy "contracts_client_select_by_email"
  on public.contracts for select
  to authenticated
  using (lower(client_email) = lower(coalesce((auth.jwt() ->> 'email'), '')));

drop policy if exists "contract_payments_admin_all" on public.contract_payments;
create policy "contract_payments_admin_all"
  on public.contract_payments for all
  to authenticated
  using (app_private.current_user_is_admin())
  with check (app_private.current_user_is_admin());

drop policy if exists "contract_payments_client_select_by_email" on public.contract_payments;
create policy "contract_payments_client_select_by_email"
  on public.contract_payments for select
  to authenticated
  using (lower(client_email) = lower(coalesce((auth.jwt() ->> 'email'), '')));

drop policy if exists "client_messages_admin_all" on public.client_messages;
create policy "client_messages_admin_all"
  on public.client_messages for all
  to authenticated
  using (app_private.current_user_is_admin())
  with check (app_private.current_user_is_admin());

drop policy if exists "client_messages_client_select_self" on public.client_messages;
create policy "client_messages_client_select_self"
  on public.client_messages for select
  to authenticated
  using (user_id = (select auth.uid()) or lower(client_email) = lower(coalesce((auth.jwt() ->> 'email'), '')));

drop policy if exists "client_messages_client_insert_self" on public.client_messages;
create policy "client_messages_client_insert_self"
  on public.client_messages for insert
  to authenticated
  with check (user_id = (select auth.uid()) and lower(client_email) = lower(coalesce((auth.jwt() ->> 'email'), '')) and direction = 'client_to_admin');

drop policy if exists "knowledge_base_public_read_published" on public.knowledge_base;
create policy "knowledge_base_public_read_published"
  on public.knowledge_base for select
  to anon, authenticated
  using (published = true or app_private.current_user_is_admin());

drop policy if exists "knowledge_base_admin_all" on public.knowledge_base;
create policy "knowledge_base_admin_all"
  on public.knowledge_base for all
  to authenticated
  using (app_private.current_user_is_admin())
  with check (app_private.current_user_is_admin());

grant usage on schema public to anon, authenticated;
grant select on public.knowledge_base to anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert on public.audit_logs to authenticated;
grant select, insert on public.website_metrics to authenticated;
grant select, insert, update, delete on public.contracts to authenticated;
grant select, insert, update, delete on public.contract_payments to authenticated;
grant select, insert, update, delete on public.client_messages to authenticated;
grant select, insert, update, delete on public.knowledge_base to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- After creating your Supabase Auth user, make yourself admin with:
-- insert into public.profiles (id, email, is_admin)
-- select id, email, true from auth.users where email = 'your-email@example.com'
-- on conflict (id) do update set is_admin = true, email = excluded.email, updated_at = now();

